### ISSUE TITLE
Queue for GPU

### ISSUE THREAD

**Issue by gimlidc** [jakub-tucek/clusterize#5]
Je dost možný, že se změnily požadavky na GPU jobs a je nyní nově potřeba udávat GPU frontu. Tj. job definovaný tímto qsub skriptem:

```
#PBS -N GPU-hello-world
#PBS -q gpu
#PBS -l walltime=6:0:0
#PBS -l select=1:ncpus=1:mem=4gb:scratch_local=1gb:ngpus=1
#PBS -o /auto/plzen1/home/gimli/tmp
#PBS -e /auto/plzen1/home/gimli/tmp

echo $PBS_JOBID
echo "Hello world!"
```

Je OK zatímco

bez řádku 2 nejde pustit:
`qsub: Job violates queue and/or server resource limits`

Bohužel clusterize tenhle parametr do qsub skriptů nedává (if GPU) ani se na něj neptá (gpu, či gpu_long jsou správný fronty).

**Comment by jakub-tucek** [comment]
Done
